name: build openwrt
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      run: |
        sudo docker rmi `docker images -q`
        sudo apt-get -y update
        sudo apt-get -y install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo apt-get -y clean
    - name: Clone source code
      run: |
        git clone https://github.com/coolsnowwolf/lede
        echo "src-git helloworld https://github.com/fw876/helloworld" >> lede/feeds.conf.default
    - name: Update feeds & Install feeds
      run: |
        cd lede
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: Load custom configuration
      run: |
        mv .config lede/.config
    - name: Download package
      run: |
        cd lede
        make defconfig
        make download -j8 || make download -j1 V=s
    - name: Compile firmware
      run: |
        cd lede
        make -j$(nproc) || make -j1 V=s
    - name: Upload firmware
      uses: actions/upload-artifact@master
      with:
        name: firmware
        path: lede/bin
